server:
  port: 8080

spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: gateway
            client-secret: D0pgFM1UBhRM20pHoJ1T8dXh0KCBjs9w
            authorization-grant-type: password

app:
  oas:
    url: /api
    spec-file-url: /openapi.yaml
