spring:
  application:
    name: warehouse

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

  jpa:
    open-in-view: false

  devtools:
    livereload:
      enabled: false

management:
  endpoints:
    web:
      exposure:
        include: '*'

server:
  port: 0

app:
  kafka:
    consumer-group: warehouse