spring:
  jpa:
    open-in-view: false
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  web:
    locale: en_US

management:
  endpoints:
    web:
      exposure:
        include: '*'

server:
  error:
    whitelabel:
      enabled: false