package com.example.eshop.catalog.client.cataloggateway;

import com.example.eshop.catalog.client.api.model.Attribute;
import com.example.eshop.catalog.client.api.model.Money;
import com.example.eshop.catalog.client.api.model.Product;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import java.util.Collections;
import java.util.List;

@Builder
@AllArgsConstructor
@EqualsAndHashCode
@Getter
// we use class in favor of record to keep getter syntax consistent with autogenerated DTO
public final class SkuWithProduct {
    private Money price;
    private String ean;
    private String productId;
    private Integer quantity;
    @Builder.Default
    private List<Attribute> attributes = Collections.emptyList();
    private Product product;
}
