spring:
  application:
    name: api-gateway

  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: gateway
            client-secret: D0pgFM1UBhRM20pHoJ1T8dXh0KCBjs9w
            authorization-grant-type: password
        provider:
          keycloak:
            issuer-uri: http://localhost:28000/auth/realms/test

  devtools:
    livereload:
      enabled: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true

app:
  oas:
    url: /api
    spec-file-url: /openapi.yaml

server:
  error:
    whitelabel:
      enabled: false