spring:
  main:
    web-application-type: none

  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer

outbox:
  data-sources:
    warehouse:
      url: jdbc:postgresql://localhost:5432/warehouse
      username: ${POSTGRES_USER:admin}
      password: ${POSTGRES_PASSWORD:admin}
      type: org.postgresql.ds.PGSimpleDataSource

---

spring.config.activate.on-profile: docker

outbox:
  data-sources:
    warehouse:
      url: jdbc:postgresql://postgres:5432/warehouse