package com.example.eshop.catalog.client.model;

import com.example.eshop.sharedkernel.domain.valueobject.Ean;
import com.example.eshop.sharedkernel.domain.valueobject.Money;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import java.util.Collections;
import java.util.List;

@Builder
@AllArgsConstructor
@NoArgsConstructor
@EqualsAndHashCode
@Getter
// we use class in favor of record to keep getter syntax consistent with autogenerated DTO
public final class SkuWithProductDto {
    private Money price;
    private Ean ean;
    private String productId;
    private Integer quantity;
    @Builder.Default
    private List<AttributeDto> attributes = Collections.emptyList();
    private ProductDto product;
}
