spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/warehouse
    username: ${POSTGRES_USER:admin}
    password: ${POSTGRES_PASSWORD:admin}

app:
  kafka:
    consumer-group: warehouse

---

spring.config.activate.on-profile: docker

spring.datasource.url: jdbc:postgresql://postgres:5432/warehouse