version: "3.9"

services:
  postgres:
    volumes:
      - ./init/postgres:/docker-entrypoint-initdb.d

  keycloak:
    environment:
      KEYCLOAK_IMPORT: /tmp/test_realm.json
    volumes:
      - ./init/keycloak:/tmp