#
# This file contains services for monitoring
#

version: "3.9"

services:
  zipkin:
    image: ghcr.io/openzipkin/zipkin:2.23.16
    container_name: eshop-zipkin
    environment:
      - STORAGE_TYPE=mem
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9093
    ports:
      - "9411:9411"
    networks:
      - app-tier

  prometheus:
    image: bitnami/prometheus:2.35.0
    container_name: eshop-prometheus
    volumes:
      - eshop-prometheus:/opt/bitnami/prometheus/data
      - ./prometheus:/etc/prometheus/
    ports:
      - "9090:9090"
    networks:
      - app-tier
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  eshop-prometheus:

networks:
  app-tier:
    name: eshop-app-tier
    driver: bridge
