#
# This file contains services for monitoring
#

version: "3.9"

services:
  zipkin:
    image: ghcr.io/openzipkin/zipkin:2.23.16
    container_name: eshop-zipkin
    environment:
      - STORAGE_TYPE=mem
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9093
    ports:
      - "9411:9411"
    networks:
      - app-tier

networks:
  app-tier:
    name: eshop-app-tier
    driver: bridge
