spring:
  application:
    name: checkout-service

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:28000/auth/realms/test

  config:
    import: configserver:http://localhost:8888

  cloud:
    config:
      fail-fast: true
      retry:
        max-attempts: 5
