server:
  port: 0
  error:
    whitelabel:
      enabled: false

spring:
  application:
    name: shopping-cart-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:28000/auth/realms/test

  devtools:
    livereload:
      enabled: false

  jpa:
    open-in-view: false

management:
  endpoints:
    web:
      exposure:
        include: '*'